print('Enter Your Name:')
Name = input()
print('Entered name is:',Name)
Name =input('Enter your name:')
print('Entered Name:',Name)
name = input("Enter Your name: ")
age = input("Enter your age:")
yob = 2024 - int(age)
print(type(age), yob)
value_01 = int(input('Enter Your Mobile Number'))
print('Entered number:',value_01)
print('Entered name:',type(value_01))
